version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  social-share:
    image: socialshare:latest
    depends_on:
      - mongodb
    ports:
      - 3000:3000

volumes:
  mongo-data:
    driver: local
